### ISSUE TITLE
Unable to get past storage permission prompt

### ISSUE THREAD

**Issue by sugiharaxo** [resucutie/localbooru#11]
Unable to get past storage permissions prompt, even if the permission is given manually

![20240510_120937](https://github.com/resucutie/localbooru/assets/20361212/c3c1431a-d462-4241-bc7a-e8fee410baad)

**System informations:**
 - Device: Galaxy S9
 - OS: Android 10

**Comment by resucutie** [comment]
Fixed in 22128c6. The issue was that on systems below SDK 32 the wrong permission would be requested, and now it properly asks for the right permission

Expect the fix to be released on 1.5.0. I should've shipped the fix on 1.4.1 but I forgot
