### ISSUE TITLE
Code licensing

### ISSUE THREAD

**Issue by ixhbinphoenix** [resucutie/localbooru#13]
Hey, thank you for working on this Project!

I was working on packaging localbooru for the [NUR](https://github.com/nix-community/NUR) (and maybe eventually nixpkgs) and noticed that the project doesn't have any license. Is this intended?
If you intend to run this project open-source, I'd highly recommend choosing a license since it allows people to modify and therefore contribute to your project. It's also a requirement for publishing on F-Droid.

Of course this is completely up to you, no pressure, just wanted to ask

P.S: Am I allowed to publish my nix package of localbooru?

**Comment by ixhbinphoenix** [comment]
thanks for the quick reply!

Regarding the legality of licensing:
I am not a lawyer and this is not legal advice. Currently, since you're the only one who wrote code, you own the full copyright on the codebase and can solely decide the license of it and all previous versions of it, so there should be no issues there. You can sometimes run into issues if you already have multiple contributors, as they all individually have to either agree to the license change or "retract" their contributions before you can change license; this is why big projects sometimes have you sign a CLA (Contributors License Agreement) so they can change the license without having to ask you.

I'm still working on a source version of the nix package (flutter support in nix is not good and I'm seemingly one of ~4 people to ever package a flutter app) but both it and the binary version (derived from the .deb) are following releases.

Unfortunately I have never worked with F-droid or flatpak, but I've heard some things about the submission process to F-droid. iirc, you submit your project to the f-droid package requests, reviewers from their team look at the source code, if it follows the [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) and how they'll build it on their servers. afaik, if it gets approved that's about everything you have to do. I'd recommend reading the [Inclusion How-To](https://f-droid.org/en/docs/Inclusion_How-To/) if you want to look more into it. There's also [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/info), a 3rd-Party f-droid repo with slightly less strict rules and from what I've heard a lot faster submission times.

**Comment by resucutie** [comment]
thanks for the answers!

well, before launching it to the nix package system, just tell me how you've managed to do it so i can approve it. also it would be better to join the discord to share the progress

if you know anyone who does know how to package flutter apps on flatpaks, tell me!

**Comment by ixhbinphoenix** [comment]
hey,
it seems like the discord link expired, could you send me a new one?
Also unfortunately I don't know anyone that has worked with flatpak or flutter

**Comment by resucutie** [comment]
oh, sorry for the delay. odd that it expired, uh 2s

**Comment by resucutie** [comment]
Forgot to say that on commti 2e22350, I've added the license to the project

All of the versions that are under that commit will follow it
