### ISSUE TITLE
Bug: Search suggestion panel gets stuck, can lead to app crash 

### ISSUE THREAD

**Issue by admbeck** [resucutie/localbooru#18]
**Describe the bug**
After searching for a tag and clicking `back` the menu may get stuck. Clicking back again multiple times leads to the app going black and becoming unusable.
![image](https://github.com/user-attachments/assets/08c59d39-c3e5-4c4b-be89-f660bdfd9861)

**To Reproduce**
1. (to be determined)
2. Search for a tag, for example rating:safe
3. Edit any tag for the image
4. Click save
5. Click on back arrow until the app goes black

**Expected behavior**
Suggestion panel should not get stuck.
When clicking back the application should eventually go to the main menu.

**Screenshots**
![image](https://github.com/user-attachments/assets/e230458b-43ad-4ffc-b517-9df6366e2acc)
![image](https://github.com/user-attachments/assets/d771b13b-e0ec-45fe-972d-9f4987240459)

**System information:**
 - Device: Desktop
 - OS: Arch Linux
 - Package: Binary
 - Version: 1.5.2

**Comment by resucutie** [comment]
May you provide a recording of the issue? It isn't exactly clear what's going on

**Comment by admbeck** [comment]
> May you provide a recording of the issue? It isn't exactly clear what's going on

I will do that as soon as I encounter it again. It is not clear to me why this happens either and there's nothing suspicious in the terminal output for the application

**Comment by admbeck** [comment]
Managed to record the effect of this bug, but not what causes it. Still can't figure out what I am doing out of the ordinary that causes this bug
https://github.com/user-attachments/assets/39082e4f-62df-4195-ab9a-6b3192473990

**Comment by resucutie** [comment]
As much as I want to fix it, I can't really do anything without a method to replicate, even if not 100% consistent. Sorry :/

**Comment by admbeck** [comment]
I think this issue could be closed unless I find a proper way to replicate it
