### ISSUE TITLE
Bug: Crash on opening webm

### ISSUE THREAD

**Issue by admbeck** [resucutie/localbooru#19]
**Describe the bug**
Upon opening an imported webm video to view application crashes with a segfault. It is important to note that the same videos are played perfectly fine on Android device in localbooru.

**To Reproduce**
1. Open any webm 
2. Wait for video to load
3. See the crash

**Expected behavior**
Videos to be played without crashing the application

**System information:**
 - Device: Desktop
 - OS: Arch Linux
 - Package: Binary
 - Version: 1.5.2

**Additional context**
Terminal output
```
flutter: Loaded booruPath with /home/beck/Applications/localbooru/booru
flutter: dynamic_color: Accent color detected.
flutter: 
media_kit: VideoOutput: video_output_new: 124888860707456
media_kit: VideoOutput: Using H/W rendering.
flutter: VideoOutput.Resize
flutter: {handle: 124888860707456, id: 104163595982864, rect: {left: 0, top: 0, width: 1, height: 1}}
flutter: NativeVideoController: Texture ID: 104163595982864
media_kit: TextureGL: Resize: (600, 750)
flutter: VideoOutput.Resize
flutter: {handle: 124888860707456, id: 104163595982864, rect: {left: 0, top: 0, width: 600, height: 750}}
zsh: segmentation fault (core dumped)  ./Applications/localbooru/localbooru

```

**Comment by admbeck** [comment]
Turning off "Display GIFs as videos" seems to have fixed the crashes for now

**Comment by resucutie** [comment]
It is probably a mediakit issue, not exactly sure. That library is extremely buggy ngl but it is the best that I have since video_player ain't available on windows, mac and linux

**Comment by resucutie** [comment]
I should probably test it. Currently LocalBooru doesn't have any protection against files that aren't images or videos

**Comment by admbeck** [comment]
> I should probably test it. Currently LocalBooru doesn't have any protection against files that aren't images or videos

But it does? It didn't allow me to add an epub. Or do you mean protection in "Import from service"?
![Screenshot_20240822_104210](https://github.com/user-attachments/assets/ccaba757-5a10-4109-8ed1-25ed2dded6e7)

**Comment by resucutie** [comment]
> > I should probably test it. Currently LocalBooru doesn't have any protection against files that aren't images or videos
> 
> But it does? It didn't allow me to add an epub. Or do you mean protection in "Import from service"?

That came from the drag & drop. Try to add the file by going on "Add images" and adding it  
I guess it also happens if you add audio files?

**Comment by admbeck** [comment]
> That came from the drag & drop. Try to add the file by going on "Add images" and adding it I guess it also happens if you add audio files?
Tested with various files. Localbooru doesn't allow to add following files via drag&drop:
- pdf
- zip
- mp3
- json
- md
- odt
- xcf
(unless I rename file to accepted extension, then it just errors out)
 
 Using "Add image", file picker prevents me from seeing these files anyway so I can't even attempt to add them.

**Comment by resucutie** [comment]
> Selective fix. Some videos still crash the application. Will test on windows as see if it's Linux specific issue

Been aware of this issue honestly. mediakit can make LocalBooru to crash when you try to navigate elsewhere. Waiting for a better video handler atm

> Tested with various files. Localbooru doesn't allow to add following files via drag&drop:

Huh, foggy memory then

**Comment by resucutie** [comment]
It isn't an issue with webm, and is instead an issue with mediakit being unstable  
I've added a webm file into LocalBooru's latest dev branch changes and although it crashes in the middle of a video's execution, it also does the same with mp4


https://github.com/user-attachments/assets/b9806972-3d14-442b-90b3-b705c817c4af
