### ISSUE TITLE
Booru selector asks for files, not folders - Linux

### ISSUE THREAD

**Issue by Soblow** [resucutie/localbooru#36]
**Describe the bug**
On Linux, attempting to select a booru folder doesn't work because it asks for files.

**To Reproduce**
1. Go on the menu to select a booru folder
2. Click on "Select an already existing booru"
3. Browse and select the folder
4. It will open the folder instead of selecting it

**Expected behavior**
Selecting a folder and validating should select the folder as a booru folder, not open it

**Screenshots**
![Peek 07-11-2024 16-26](https://github.com/user-attachments/assets/206a3c9e-f7f1-4dd2-96d7-463e4093ae34)

**System informations:**
 - Device: Laptop
 - OS: Debian Trixie/sid testing
 - Package: deb package
 - Version: 1.6.0-prerelease2 & 3

**Additional context**
I have no idea if it's specific to my setup/install...

**Comment by resucutie** [comment]
Seems like an issue with your system tbh. You can try to test if it is an issue with file_picker by building [this example project](https://github.com/miguelpruivo/flutter_file_picker/tree/master/example) if you have the flutter toolchain
![image](https://github.com/user-attachments/assets/512ed29a-7ff0-4196-9665-0d49cf25847b)

**Comment by Soblow** [comment]
Same issue with the example project.
I guess it's either a problem with my setup or with the plugin.

I'll report it to the plugin repo once I have time, and I'll link it here.

Thanks.
